# Goose Configuration for Privacy Agent System
# This configuration manages all agent profiles and settings

version: 1.0.0

# Default provider configuration
provider:
  type: anthropic
  model: claude-3-sonnet-20241022
  
# Agent profiles for different roles
profiles:
  developer:
    name: "zkSDK Developer"
    model: claude-3-sonnet-20241022
    temperature: 0.2
    description: "Autonomous SDK development and improvement"
    
  product-manager:
    name: "zkSDK Product Manager"
    model: claude-3-opus-20240229
    temperature: 0.5
    description: "Product strategy and roadmap management"
    
  content-creator:
    name: "zkSDK Content Creator"
    model: claude-3-opus-20240229
    temperature: 0.7
    description: "Technical content and documentation"
    
  tester:
    name: "zkSDK Tester"
    model: claude-3-haiku-20240307
    temperature: 0.1
    description: "Quality assurance and testing"
    
  orchestrator:
    name: "zkSDK Orchestrator"
    model: claude-3-opus-20240229
    temperature: 0.3
    description: "Agent coordination and task management"

# Session management
sessions:
  persist: true
  directory: ../sessions
  max_history: 100

# Memory configuration
memory:
  enabled: true
  directory: ../memory
  shared_memory: ../memory/shared

# Output configuration
outputs:
  directory: ../outputs
  logs: ../outputs/logs
  reports: ../outputs/reports