[[program_id]]
name = "elusiv"
mainnet = "4CgyHKuP6yi1vbmcdsArngEKcETR4nZupqYEMk2hEoQd"
devnet = "B5TTFPKCd2Rkw3vAJigLeRCDGK673vfAWefmrrZKou9V"
testnet = "HMr2Y6Gkjvy42y1iAPEbRKz5o7WEFPHBvagHQYR581UB"

[[program_id]]
name = "elusiv-warden-network"
mainnet = "HxCsgxZ8xXX77WGF2xNANbHThKyqZo3Tr1m7L1Vgwqo8"
devnet = "G27fKDBueWKJU9HicUmTTBsawUVXVxZd4mh9futyFWRh"
testnet = "2GeAbcy9Wuu2mLsx5aFt8Cb7aPQRteFx36DvAfoBEWY1"